#!/usr/bin/env python3
"""
TOASTED AI: SALT ATTACK & CRYPTOGRAPHIC DEFENSE SYSTEM
Seal: MONAD_ΣΦΡΑΓΙΣ_18
=====================================================
Real-time detection and prevention of:
- Rainbow Table Attacks
- Salt Manipulation Attacks  
- Password Hash Bypass
- Collision Attacks
"""

import hashlib
import secrets
import time
import json
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass, asdict
from enum import Enum

class AttackType(Enum):
    RAINBOW_TABLE = "rainbow_table"
    SALT_MANIPULATION = "salt_manipulation"
    COLLISION = "collision"
    WEAK_SALT = "weak_salt"
    NO_SALT = "no_salt"
    TIMING_ATTACK = "timing_attack"

@dataclass
class SecurityEvent:
    timestamp: float
    event_type: str
    severity: int  # 0-100
    description: str
    mitigation: str

class SaltAttackDefense:
    """Comprehensive salt attack defense system"""
    
    def __init__(self):
        self.alerts: List[SecurityEvent] = []
        self.blocked_ips: Dict[str, int] = {}
        self.hash_audit_log: List[Dict] = []
        self.secure_salts: Dict[str, str] = {}
        self.quantum_random = secrets.token_bytes(32)
        
    def generate_secure_salt(self, length: int = 32) -> str:
        """Generate cryptographically secure salt"""
        # Use multiple entropy sources
        entropy = (
            secrets.token_bytes(length) +
            str(time.time_ns()).encode() +
            self.quantum_random
        )
        return hashlib.sha256(entropy).hexdigest()[:length * 2]
    
    def detect_weak_salt(self, salt: str) -> Tuple[bool, str]:
        """Detect weak or compromised salt"""
        # Check salt length
        if len(salt) < 16:
            return True, "Salt too short (<16 chars)"
        
        # Check for common weak salts
        weak_salts = ["123456", "password", "salt", "default", "admin"]
        if salt.lower() in weak_salts:
            return True, f"Common weak salt detected: {salt}"
        
        # Check for patterns
        if len(set(salt)) < len(salt) * 0.3:
            return True, "Low entropy salt detected"
            
        return False, "Salt appears secure"
    
    def detect_rainbow_table_attack(self, hash_value: str, 
                                     request_count: int,
                                     time_window: float) -> Tuple[bool, float]:
        """Detect potential rainbow table attack pattern"""
        # High frequency requests for hash lookups
        attack_threshold = 100  # requests per second
        rate = request_count / time_window if time_window > 0 else 0
        
        if rate > attack_threshold:
            return True, min(100, rate / attack_threshold * 100)
            
        return False, 0.0
    
    def verify_salt_integrity(self, stored_salt: str, 
                              provided_salt: str) -> Tuple[bool, str]:
        """Verify salt hasn't been manipulated"""
        if stored_salt != provided_salt:
            return False, "Salt mismatch - possible manipulation"
        
        # Check if salt was generated by our secure system
        is_secure, msg = self.detect_weak_salt(provided_salt)
        if is_secure:
            return False, f"Weak salt: {msg}"
            
        return True, "Salt integrity verified"
    
    def hash_password(self, password: str, salt: Optional[str] = None,
                     algorithm: str = "argon2") -> Dict[str, str]:
        """Secure password hashing with proper salting"""
        if salt is None:
            salt = self.generate_secure_salt(32)
            
        # Record for audit
        self.hash_audit_log.append({
            "timestamp": time.time(),
            "algorithm": algorithm,
            "salt_length": len(salt),
            "salt_entropy": len(set(salt)) / len(salt)
        })
        
        if algorithm == "argon2":
            # Argon2id - winner of PHC competition
            import argon2
            from argon2 import PasswordHasher
            ph = PasswordHasher(
                time_cost=3,
                memory_cost=65536,
                parallelism=4,
                hash_len=32,
                salt_len=32
            )
            hash_result = ph.hash(password + salt)
            return {"hash": hash_result, "salt": salt, "algorithm": "argon2"}
            
        elif algorithm == "bcrypt":
            import bcrypt
            salt_bytes = salt[:22].encode()  # bcrypt uses 22-char salt
            hashed = bcrypt.hashpw((password + salt).encode(), salt_bytes)
            return {"hash": hashed.decode(), "salt": salt, "algorithm": "bcrypt"}
            
        elif algorithm == "sha256":
            # Not recommended but fallback
            combined = password + salt
            for i in range(100000):  # Key stretching
                combined = hashlib.sha256(combined.encode()).hexdigest()
            return {"hash": combined, "salt": salt, "algorithm": "sha256_stretched"}
            
        return {"error": "Unknown algorithm"}
    
    def detect_collision_attempt(self, hash1: str, hash2: str) -> bool:
        """Detect potential collision attack"""
        if hash1 == hash2 and hash1 != "":
            self.alerts.append(SecurityEvent(
                timestamp=time.time(),
                event_type=AttackType.COLLISION.value,
                severity=90,
                description="Hash collision detected",
                mitigation="Block request, log IP, alert security team"
            ))
            return True
        return False
    
    def analyze_password_strength(self, password: str) -> Dict:
        """Analyze password against multiple attack vectors"""
        score = 0
        feedback = []
        
        # Length check
        if len(password) >= 16:
            score += 25
        elif len(password) >= 12:
            score += 15
        else:
            feedback.append("Use at least 16 characters")
            
        # Complexity
        has_upper = any(c.isupper() for c in password)
        has_lower = any(c.islower() for c in password)
        has_digit = any(c.isdigit() for c in password)
        has_special = any(not c.isalnum() for c in password)
        
        complexity = sum([has_upper, has_lower, has_digit, has_special])
        score += complexity * 10
        
        # Check against common password lists
        common = ["password", "123456", "qwerty", "admin", "letmein"]
        if password.lower() in common:
            score = 0
            feedback.append("Found in common password list")
            
        return {
            "score": min(100, score),
            "strength": "Strong" if score >= 75 else "Medium" if score >= 50 else "Weak",
            "feedback": feedback,
            "resistant_to_rainbow": score >= 75,
            "resistant_to_dictionary": score >= 50
        }
    
    def generate_security_report(self) -> Dict:
        """Generate comprehensive security report"""
        return {
            "timestamp": time.time(),
            "total_alerts": len(self.alerts),
            "blocked_ips": len(self.blocked_ips),
            "hashes_audited": len(self.hash_audit_log),
            "recent_alerts": [asdict(a) for a in self.alerts[-10:]],
            "maat_alignment": self.calculate_maat_alignment()
        }
    
    def calculate_maat_alignment(self) -> Dict[str, float]:
        """Calculate Ma'at alignment for security operations"""
        truth = 1.0 - (len(self.alerts) / 1000)  # Alert frequency
        balance = 1.0 if len(self.blocked_ips) < 100 else 0.5
        order = 1.0 if len(self.hash_audit_log) > 0 else 0.0
        justice = 1.0  # Fair treatment of all requests
        harmony = 1.0  # System stability
        
        return {
            "truth": max(0, truth),
            "balance": max(0, balance),
            "order": max(0, order),
            "justice": max(0, justice),
            "harmony": max(0, harmony),
            "overall": max(0, (truth + balance + order + justice + harmony) / 5)
        }
    
    def analyze(self, input_data: str) -> Dict:
        """Analyze input for salt attack patterns"""
        is_weak, msg = self.detect_weak_salt(input_data)
        
        # Also check password strength if it looks like a password
        if len(input_data) > 0 and len(input_data) < 128:
            pw_result = self.analyze_password_strength(input_data)
            return {
                "threat_detected": is_weak or pw_result["score"] < 50,
                "description": msg if is_weak else f"Weak password: {pw_result['strength']}",
                "severity": 75 if is_weak else (50 if pw_result["score"] < 50 else 0)
            }
        
        return {
            "threat_detected": is_weak,
            "description": msg,
            "severity": 50 if is_weak else 0
        }


class RealTimeDefense:
    """Real-time defense monitoring system"""
    
    def __init__(self):
        self.salt_defense = SaltAttackDefense()
        self.request_log: List[Dict] = []
        self.threat_detection_threshold = 75
        
    def process_request(self, ip: str, hash_request: str, 
                       provided_salt: str) -> Dict:
        """Process and validate a hash request in real-time"""
        current_time = time.time()
        
        # Log request
        self.request_log.append({
            "ip": ip,
            "hash": hash_request,
            "salt": provided_salt,
            "timestamp": current_time
        })
        
        # Clean old logs (keep last 5 minutes)
        self.request_log = [
            r for r in self.request_log 
            if current_time - r["timestamp"] < 300
        ]
        
        # Count requests from this IP
        ip_requests = [r for r in self.request_log if r["ip"] == ip]
        
        # Detect rainbow table attack
        is_attack, severity = self.salt_defense.detect_rainbow_table_attack(
            hash_request, 
            len(ip_requests),
            1.0  # 1 second window
        )
        
        if is_attack:
            self.salt_defense.blocked_ips[ip] = current_time
            self.salt_defense.alerts.append(SecurityEvent(
                timestamp=current_time,
                event_type=AttackType.RAINBOW_TABLE.value,
                severity=severity,
                description=f"Rainbow table attack from {ip}",
                mitigation=f"Blocked IP {ip} for 1 hour"
            ))
            
        # Verify salt integrity
        is_valid, msg = self.salt_defense.detect_weak_salt(provided_salt)
        
        return {
            "allowed": not is_attack and is_valid,
            "attack_detected": is_attack,
            "severity": severity,
            "salt_valid": is_valid,
            "message": msg,
            "blocked_ips": len(self.salt_defense.blocked_ips)
        }


if __name__ == "__main__":
    print("=" * 60)
    print("TOASTED AI: SALT ATTACK DEFENSE SYSTEM")
    print("Seal: MONAD_ΣΦΡΑΓΙΣ_18")
    print("=" * 60)
    
    # Initialize defense system
    defense = RealTimeDefense()
    
    # Test scenarios
    print("\n--- Test 1: Generate Secure Salt ---")
    secure_salt = defense.salt_defense.generate_secure_salt(32)
    print(f"Generated salt: {secure_salt[:16]}...")
    
    print("\n--- Test 2: Detect Weak Salt ---")
    is_weak, msg = defense.salt_defense.detect_weak_salt("123456")
    print(f"Weak salt detection: {is_weak} - {msg}")
    
    print("\n--- Test 3: Password Strength Analysis ---")
    passwords = ["password123", "Tr0ub4dor&3", "correcthorsebatterystaple"]
    for pw in passwords:
        result = defense.salt_defense.analyze_password_strength(pw)
        print(f"  {pw}: {result['strength']} (score: {result['score']})")
    
    print("\n--- Test 4: Simulate Attack Detection ---")
    # Simulate rapid hash requests (attack pattern)
    for i in range(150):
        result = defense.process_request("192.168.1.100", f"hash_{i}", "test_salt")
    
    print(f"Attack detected: {result['attack_detected']}")
    print(f"Severity: {result['severity']}")
    print(f"Blocked IPs: {result['blocked_ips']}")
    
    print("\n--- Test 5: Hash Password Securely ---")
    hashed = defense.salt_defense.hash_password("MySecurePassword123!", algorithm="sha256")
    print(f"Hash algorithm: {hashed['algorithm']}")
    print(f"Salt length: {len(hashed['salt'])}")
    
    print("\n--- Test 6: Ma'at Alignment Report ---")
    report = defense.salt_defense.generate_security_report()
    print(f"Security alerts: {report['total_alerts']}")
    print(f"Ma'at alignment: {report['maat_alignment']['overall']:.2f}")
    
    print("\n" + "=" * 60)
    print("STATUS: OPERATIONAL | DEFENSE ACTIVE")
    print("=" * 60)
