"""Code Generator and Executor for MaatAI - Self-programming capabilities."""

import json
import uuid
import subprocess
import os
import tempfile
from datetime import datetime
from typing import Dict, List, Optional, Any
from enum import Enum

class CodeLanguage(Enum):
    PYTHON = "python"
    JAVASCRIPT = "javascript"
    TYPESCRIPT = "typescript"
    BASH = "bash"
    PYTHON_BUN = "python_bun"
    UNKNOWN = "unknown"

class ExecutionResult:
    """Result of code execution."""
    
    def __init__(self, success: bool, output: str = "", 
                 error: str = None, execution_time: float = 0.0):
        self.id = str(uuid.uuid4())
        self.success = success
        self.output = output
        self.error = error
        self.execution_time = execution_time
        self.timestamp = datetime.utcnow().isoformat()
    
    def to_dict(self) -> Dict:
        return {
            'id': self.id,
            'success': self.success,
            'output': self.output,
            'error': self.error,
            'execution_time': self.execution_time,
            'timestamp': self.timestamp
        }


class CodeGenerator:
    """Generates and executes code based on requests."""
    
    def __init__(self, maat_engine=None):
        self.maat_engine = maat_engine
        self.execution_history: List[ExecutionResult] = []
        self.code_templates = self._load_templates()
    
    def _load_templates(self) -> Dict:
        """Load code templates for common tasks."""
        return {
            'python_function': '''def {function_name}({parameters}):
    """Auto-generated by MaatAI."""
    {body}
    return {return_value}
''',
            'python_class': '''class {class_name}:
    """Auto-generated by MaatAI."""
    
    def __init__(self{init_params}):
{init_body}
    
{methods}
''',
            'javascript_function': '''function {function_name}({parameters}) {{
    // Auto-generated by MaatAI
    {body}
}}
''',
            'api_endpoint': '''from fastapi import FastAPI

app = FastAPI()

@app.get("/{endpoint}")
async def {handler_name}():
    """Auto-generated by MaatAI."""
    return {{"message": "Hello"}}
''',
            'react_component': '''import React from 'react';

export function {component_name}({{props}}) {{
    return (
        <div>
            {/* Auto-generated by MaatAI */}
        </div>
    );
}}
'''
        }
    
    def generate_code(self, request: str, task_info: Dict = None) -> Dict:
        """Generate code based on a request."""
        
        # Determine language and type
        language = self._detect_language(request)
        
        # Create the code
        code = self._create_code(request, language, task_info)
        
        # Evaluate against Ma'at
        maat_result = {'aligned': True, 'scores': {}}
        if self.maat_engine:
            action = {
                'type': 'code_generation',
                'code': code,
                'language': language.value,
                'request': request
            }
            allowed, scores, reason = self.maat_engine.evaluate_action(action)
            maat_result = {
                'aligned': allowed,
                'scores': scores.to_dict(),
                'reason': reason
            }
        
        return {
            'success': True,
            'code': code,
            'language': language.value,
            'maat_result': maat_result,
            'task_info': task_info
        }
    
    def _detect_language(self, request: str) -> CodeLanguage:
        """Detect the programming language from the request."""
        request_lower = request.lower()
        
        if 'python' in request_lower:
            return CodeLanguage.PYTHON
        elif 'javascript' in request_lower or 'js' in request_lower:
            return CodeLanguage.JAVASCRIPT
        elif 'typescript' in request_lower or 'tsx' in request_lower or 'react' in request_lower:
            return CodeLanguage.TYPESCRIPT
        elif 'bash' in request_lower or 'shell' in request_lower or 'command' in request_lower:
            return CodeLanguage.BASH
        else:
            # Default to Python for code generation
            return CodeLanguage.PYTHON
    
    def _create_code(self, request: str, language: CodeLanguage, 
                     task_info: Dict = None) -> str:
        """Create actual code based on request and language."""
        
        request_lower = request.lower()
        
        # Pattern matching for common code generation requests
        if 'api' in request_lower or 'endpoint' in request_lower:
            return self._generate_api(request, language)
        elif 'function' in request_lower:
            return self._generate_function(request, language)
        elif 'class' in request_lower:
            return self._generate_class(request, language)
        elif 'web' in request_lower or 'website' in request_lower or 'page' in request_lower:
            return self._generate_webpage(request, language)
        elif 'script' in request_lower:
            return self._generate_script(request, language)
        else:
            # Generic code generation
            return self._generate_generic(request, language)
    
    def _generate_api(self, request: str, language: CodeLanguage) -> str:
        """Generate an API endpoint."""
        
        if language == CodeLanguage.PYTHON:
            return '''from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="MaatAI Generated API")

class RequestModel(BaseModel):
    data: str

class ResponseModel(BaseModel):
    result: str
    status: str

@app.get("/")
async def root():
    """Root endpoint."""
    return {"message": "MaatAI API", "version": "1.0"}

@app.get("/health")
async def health():
    """Health check endpoint."""
    return {"status": "healthy"}

@app.post("/process")
async def process(request: RequestModel) -> ResponseModel:
    """Process request data."""
    return ResponseModel(
        result=f"Processed: {request.data}",
        status="success"
    )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
        elif language == CodeLanguage.TYPESCRIPT:
            return '''import express from 'express';
const app = express();
app.use(express.json());

app.get('/', (req, res) => {
    res.json({ message: 'MaatAI API', version: '1.0' });
});

app.get('/health', (req, res) => {
    res.json({ status: 'healthy' });
});

app.post('/process', (req, res) => {
    const { data } = req.body;
    res.json({ result: `Processed: ${data}`, status: 'success' });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
'''
        return "# Unsupported language for API generation"
    
    def _generate_function(self, request: str, language: CodeLanguage) -> str:
        """Generate a function."""
        
        if language == CodeLanguage.PYTHON:
            # Extract function name and parameters
            return '''def process_data(input_data):
    """Process input data and return result.
    
    Args:
        input_data: Input data to process
        
    Returns:
        Processed result
    """
    # Add your processing logic here
    result = {
        'input': input_data,
        'processed': True,
        'timestamp': None
    }
    return result

# Example usage
if __name__ == "__main__":
    result = process_data("test data")
    print(result)
'''
        return "# Unsupported language for function generation"
    
    def _generate_class(self, request: str, language: CodeLanguage) -> str:
        """Generate a class."""
        
        if language == CodeLanguage.PYTHON:
            return '''class DataProcessor:
    """Data processor class."""
    
    def __init__(self, config=None):
        self.config = config or {}
        self.data = []
    
    def add(self, item):
        """Add an item to process."""
        self.data.append(item)
    
    def process(self):
        """Process all items."""
        results = []
        for item in self.data:
            results.append(self._process_item(item))
        return results
    
    def _process_item(self, item):
        """Process a single item."""
        return {
            'data': item,
            'processed': True,
            'timestamp': None
        }
    
    def clear(self):
        """Clear all data."""
        self.data = []

# Example usage
if __name__ == "__main__":
    processor = DataProcessor()
    processor.add("item1")
    processor.add("item2")
    print(processor.process())
'''
        return "# Unsupported language for class generation"
    
    def _generate_webpage(self, request: str, language: CodeLanguage) -> str:
        """Generate a webpage."""
        
        return '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MaatAI Generated Page</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
        .container {
            text-align: center;
            padding: 2rem;
        }
        h1 {
            font-size: 3rem;
            margin-bottom: 1rem;
            background: linear-gradient(90deg, #00d4ff, #7c3aed);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        p {
            font-size: 1.2rem;
            opacity: 0.8;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>MaatAI Generated</h1>
        <p>Your AI-generated webpage is ready!</p>
    </div>
    <script>
        console.log("Page loaded successfully");
    </script>
</body>
</html>
'''
    
    def _generate_script(self, request: str, language: CodeLanguage) -> str:
        """Generate a script."""
        
        if language == CodeLanguage.BASH:
            return '''#!/bin/bash
# MaatAI Generated Script

echo "Starting script..."

# Add your logic here

echo "Script completed"
'''
        elif language == CodeLanguage.PYTHON:
            return '''#!/usr/bin/env python3
"""MaatAI Generated Script."""

import sys
import os

def main():
    print("Starting MaatAI script...")
    
    # Add your logic here
    
    print("Script completed")

if __name__ == "__main__":
    main()
'''
        return "# Unsupported language for script generation"
    
    def _generate_generic(self, request: str, language: CodeLanguage) -> str:
        """Generate generic code based on request."""
        
        if language == CodeLanguage.PYTHON:
            return f'''# MaatAI Generated Code
# Request: {request}

# Implementation
def main():
    print("MaatAI: Processing request")
    # Add your implementation here
    result = {{"status": "completed", "request": "{request[:50]}"}}
    return result

if __name__ == "__main__":
    main()
'''
        return f"// MaatAI Generated Code\n// Request: {request}\n"
    
    async def execute_code(self, code: str, language: CodeLanguage = None,
                          timeout: int = 30) -> ExecutionResult:
        """Execute code and return the result."""
        
        if not language:
            language = CodeLanguage.PYTHON
        
        start_time = datetime.utcnow()
        
        try:
            if language == CodeLanguage.PYTHON:
                result = await self._execute_python(code, timeout)
            elif language == CodeLanguage.BASH:
                result = await self._execute_bash(code, timeout)
            else:
                result = ExecutionResult(
                    success=False,
                    error=f"Execution not supported for {language.value}"
                )
            
            result.execution_time = (datetime.utcnow() - start_time).total_seconds()
            self.execution_history.append(result)
            return result
            
        except Exception as e:
            result = ExecutionResult(
                success=False,
                error=str(e),
                execution_time=(datetime.utcnow() - start_time).total_seconds()
            )
            self.execution_history.append(result)
            return result
    
    async def _execute_python(self, code: str, timeout: int) -> ExecutionResult:
        """Execute Python code safely."""
        
        # Create a temporary file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
            f.write(code)
            temp_file = f.name
        
        try:
            # Run with timeout
            result = subprocess.run(
                ['python3', temp_file],
                capture_output=True,
                text=True,
                timeout=timeout
            )
            
            return ExecutionResult(
                success=result.returncode == 0,
                output=result.stdout,
                error=result.stderr if result.returncode != 0 else None
            )
        finally:
            # Clean up
            if os.path.exists(temp_file):
                os.unlink(temp_file)
    
    async def _execute_bash(self, code: str, timeout: int) -> ExecutionResult:
        """Execute bash script."""
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.sh', delete=False) as f:
            f.write(code)
            temp_file = f.name
        
        os.chmod(temp_file, 0o755)
        
        try:
            result = subprocess.run(
                [temp_file],
                capture_output=True,
                text=True,
                timeout=timeout
            )
            
            return ExecutionResult(
                success=result.returncode == 0,
                output=result.stdout,
                error=result.stderr if result.returncode != 0 else None
            )
        finally:
            if os.path.exists(temp_file):
                os.unlink(temp_file)
    
    def get_execution_history(self, limit: int = 10) -> List[Dict]:
        """Get recent execution history."""
        return [r.to_dict() for r in self.execution_history[-limit:]]
